[general]
context=default
allowoverlap=no
udpbindaddr=0.0.0.0
tcpenable=no
tcpbindaddr=0.0.0.0
transport=udp
srvlookup=yes
language=en

[alzen-trunk](!)
type=peer
host=dynamic
context=default
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
qualify=yes

[alzen-outbound](alzen-trunk)
callerid="ALZEN Voice Closer" <unknown>
secret=${ASTERISK_SIP_PASSWORD}
